@startuml "processFlow"

scale 2048 width
skinparam wrapwidth 200
skinparam maxMessageSize 500
skinparam backgroundColor #FFFFFF

title Rockfish Conservation App Process Flow

class Home {
    Why important
    What we do
    How we do it
}

class Species {
    Profiles of species
}


class Training {
    Identification game
}


class Creel {
    Community submitted catch data
}


class Fishing {
    Safe gear, catching, and releasing
}

class Regulations {
    How to get involved in making change
}

Home-->Creel
Species<--Home
Training<--Home
Home-->Fishing
Home-->Regulations

note left of Species: fishbase.org API
note right of Training: elaborate on msyphus.github.io/fish-finder
note top of Creel: Database CRUD
note bottom of Fishing: Make game instead of info page?
note "External links; maybe scrape data" as data
note "Could save species from profiles list that are used to populate the game" as idea1
note "Could use the Creel data to populate the game so players are practicing on what's most likely to be caught" as idea2
data .. Fishing
data .. Regulations
Species ..> idea1
idea1 ..> Training
Creel ..> idea2
idea2 ..> Training


@enduml
